name: Build R1 Firmware
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - run: pip install --upgrade platformio
      - run: pio run -e RAK_4631_companion_radio_ble
      - run: python3 bin/uf2conv/uf2conv.py .pio/build/RAK_4631_companion_radio_ble/firmware.hex -c -o firmware.uf2 -f 0xADA52840
      - uses: actions/upload-artifact@v7
        with:
          name: r1-firmware
          path: firmware.uf2
